[package]
name = "vtmk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.9.0+zstd.1.5.0"
uuid = "0.8.2"

[lib]
name = "fileadd"
path = "src/file-add.rs"
